.TH "__GLXEvent" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLXPbufferClobberEvent\fP \fBglxpbufferclobber\fP"
.br
.ti -1c
.RI "long \fBpad\fP [24]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 278 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGLXPbufferClobberEvent\fP __GLXEvent::glxpbufferclobber"

.PP
Definition at line 279 of file glxew\&.h\&.
.SS "long __GLXEvent::pad[24]"

.PP
Definition at line 280 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
