.TH "_GPU_DEVICE" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GPU_DEVICE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wglew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBcb\fP"
.br
.ti -1c
.RI "CHAR \fBDeviceName\fP [32]"
.br
.ti -1c
.RI "CHAR \fBDeviceString\fP [128]"
.br
.ti -1c
.RI "DWORD \fBFlags\fP"
.br
.ti -1c
.RI "RECT \fBrcVirtualScreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 959 of file wglew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "DWORD _GPU_DEVICE::cb"

.PP
Definition at line 960 of file wglew\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceName[32]"

.PP
Definition at line 961 of file wglew\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceString[128]"

.PP
Definition at line 962 of file wglew\&.h\&.
.SS "DWORD _GPU_DEVICE::Flags"

.PP
Definition at line 963 of file wglew\&.h\&.
.SS "RECT _GPU_DEVICE::rcVirtualScreen"

.PP
Definition at line 964 of file wglew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
