.TH "ACTK::UniformUI" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::UniformUI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UniformOGL3x\&.h>\fP
.PP
Inherits \fBACTK::UniformOGL3x< unsigned int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniformUI\fP (\fBint\fP \fBlocation\fP, \fBUniformDatatype\fP datatype, \fBint\fP \fBcount\fP, \fBICleanableObserver\fP *observer)"
.br
.ti -1c
.RI "\fBvoid\fP \fBclean\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 164 of file UniformOGL3x\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ACTK::UniformUI::UniformUI (\fBint\fPlocation, \fBUniformDatatype\fPdatatype, \fBint\fPcount, \fBICleanableObserver\fP *observer)"

.PP
Definition at line 9 of file UniformUIOGL3x\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ACTK::UniformUI::clean ()\fC [virtual]\fP"

.PP
Implements \fBACTK::UniformOGL3x< unsigned int >\fP\&.
.PP
Definition at line 35 of file UniformUIOGL3x\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
