.TH "ACTK::ClearState" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::ClearState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClearState\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClearState\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBClearState\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBClearState\fP &right)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorMask\fP \fBColorMask\fP"
.br
.ti -1c
.RI "bool \fBDepthMask\fP"
.br
.ti -1c
.RI "\fBClearBuffers\fP \fBBuffers\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBColor\fP"
.br
.ti -1c
.RI "float \fBDepth\fP"
.br
.ti -1c
.RI "int \fBStencil\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file ClearState\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ACTK::ClearState::ClearState ()\fC [inline]\fP"

.PP
Definition at line 56 of file ClearState\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ACTK::ClearState::operator!= (const \fBClearState\fP &right)\fC [inline]\fP"

.PP
Definition at line 84 of file ClearState\&.h\&.
.SS "bool ACTK::ClearState::operator== (const \fBClearState\fP &right)\fC [inline]\fP"

.PP
Definition at line 73 of file ClearState\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBClearBuffers\fP ACTK::ClearState::Buffers"

.PP
Definition at line 68 of file ClearState\&.h\&.
.SS "\fBColor\fP ACTK::ClearState::Color"

.PP
Definition at line 69 of file ClearState\&.h\&.
.SS "\fBColorMask\fP ACTK::ClearState::ColorMask"

.PP
Definition at line 65 of file ClearState\&.h\&.
.SS "float ACTK::ClearState::Depth"

.PP
Definition at line 70 of file ClearState\&.h\&.
.SS "bool ACTK::ClearState::DepthMask"

.PP
Definition at line 66 of file ClearState\&.h\&.
.SS "int ACTK::ClearState::Stencil"

.PP
Definition at line 71 of file ClearState\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
