.TH "ACTK::TypeConverterOGL3x" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::TypeConverterOGL3x \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TypeConverterOGL3x\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBUniformDatatype\fP \fBToActiveUniformDatatype\fP (\fBGLenum\fP \fBtype\fP)"
.br
.ti -1c
.RI "static \fBGLenum\fP \fBTo\fP (\fBPrimitiveType\fP \fBtype\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TypeConverterOGL3x\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGLenum\fP ACTK::TypeConverterOGL3x::To (\fBPrimitiveType\fPtype)\fC [static]\fP"

.PP
Definition at line 114 of file TypeConverterOGL3x\&.cpp\&.
.SS "\fBUniformDatatype\fP ACTK::TypeConverterOGL3x::ToActiveUniformDatatype (\fBGLenum\fPtype)\fC [static]\fP"

.PP
Definition at line 9 of file TypeConverterOGL3x\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
