.TH "ACTK::RenderDeviceManager" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::RenderDeviceManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RenderDeviceManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderDevicePtr\fP \fBcreateDevice\fP (\fBAPI\fP api)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRenderDeviceManager\fP & \fBgetInstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderDeviceManager\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file RenderDeviceManager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ACTK::RenderDeviceManager::RenderDeviceManager ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 17 of file RenderDeviceManager\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRenderDevicePtr\fP ACTK::RenderDeviceManager::createDevice (\fBAPI\fPapi)"

.SS "static \fBRenderDeviceManager\fP& ACTK::RenderDeviceManager::getInstance ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
