.TH "ACTK::ShaderObjectOGL3x" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::ShaderObjectOGL3x \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ShaderObjectOGL3x\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderObjectOGL3x\fP (unsigned \fBint\fP shaderType, const \fBstd::string\fP &\fBsource\fP)"
.br
.ti -1c
.RI "\fB~ShaderObjectOGL3x\fP ()"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBGetShaderHandle\fP ()"
.br
.ti -1c
.RI "bool \fBIsReady\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ShaderObjectOGL3x\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ACTK::ShaderObjectOGL3x::ShaderObjectOGL3x (unsigned \fBint\fPshaderType, const \fBstd::string\fP &source)"

.PP
Definition at line 7 of file ShaderObjectOGL3x\&.cpp\&.
.SS "ACTK::ShaderObjectOGL3x::~ShaderObjectOGL3x ()"

.PP
Definition at line 32 of file ShaderObjectOGL3x\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned \fBint\fP ACTK::ShaderObjectOGL3x::GetShaderHandle ()"

.PP
Definition at line 37 of file ShaderObjectOGL3x\&.cpp\&.
.SS "bool ACTK::ShaderObjectOGL3x::IsReady ()"

.PP
Definition at line 42 of file ShaderObjectOGL3x\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
