.TH "C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/ACTK.h" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/ACTK.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Logger\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBACTK::Color\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_LEVEL\fP   \fBLOG_LEVEL_ALL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG_LEVEL   \fBLOG_LEVEL_ALL\fP"

.PP
Definition at line 5 of file ACTK\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
