.TH "ACTK::ICleanable" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::ICleanable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICleanable\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ICleanable\fP ()"
.br
.ti -1c
.RI "virtual void \fBclean\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ICleanable\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ACTK::ICleanable::~ICleanable ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 8 of file ICleanable\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ACTK::ICleanable::clean ()\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
