.TH "ACTK::RenderDeviceD3D11" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACTK::RenderDeviceD3D11 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RenderDeviceD3D11\&.h>\fP
.PP
Inherits \fBACTK::IRenderDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderDeviceD3D11\fP (HINSTANCE hInstance)"
.br
.ti -1c
.RI "\fB~RenderDeviceD3D11\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrelease\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBGraphicsWindowPtr\fP \fBcreateWindow\fP (unsigned \fBint\fP \fBwidth\fP, unsigned \fBint\fP \fBheight\fP, const \fBstd::string\fP &title, \fBWindowType\fP windowType)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file RenderDeviceD3D11\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ACTK::RenderDeviceD3D11::RenderDeviceD3D11 (HINSTANCEhInstance)"

.PP
Definition at line 11 of file RenderDeviceD3D11\&.cpp\&.
.SS "ACTK::RenderDeviceD3D11::~RenderDeviceD3D11 (\fBvoid\fP)\fC [inline]\fP"

.PP
Definition at line 15 of file RenderDeviceD3D11\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGraphicsWindowPtr\fP ACTK::RenderDeviceD3D11::createWindow (unsigned \fBint\fPwidth, unsigned \fBint\fPheight, const \fBstd::string\fP &title, \fBWindowType\fPwindowType)\fC [virtual]\fP"

.PP
Implements \fBACTK::IRenderDevice\fP\&.
.PP
Definition at line 53 of file RenderDeviceD3D11\&.cpp\&.
.SS "\fBvoid\fP ACTK::RenderDeviceD3D11::release (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implements \fBACTK::IRenderDevice\fP\&.
.PP
Definition at line 34 of file RenderDeviceD3D11\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
