.TH "bug" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBMember \fBglfwSetMonitorCallback\fP (GLFWmonitorfun cbfun)\fP" 1c
\fBX11:\fP This callback is not yet called on monitor configuration changes\&. 
.IP "\fBMember \fBglfwSetWindowPos\fP (GLFWwindow *window, int xpos, int ypos)\fP" 1c
\fBX11:\fP Some window managers ignore the set position of hidden (i\&.e\&. unmapped) windows, instead placing them where it thinks is appropriate once they are shown\&.
.PP

