.TH "Mouse buttons" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mouse buttons \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_1\fP   0"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_2\fP   1"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_3\fP   2"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_4\fP   3"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_5\fP   4"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_6\fP   5"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_7\fP   6"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_8\fP   7"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_LAST\fP   \fBGLFW_MOUSE_BUTTON_8\fP"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_LEFT\fP   \fBGLFW_MOUSE_BUTTON_1\fP"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_RIGHT\fP   \fBGLFW_MOUSE_BUTTON_2\fP"
.br
.ti -1c
.RI "#define \fBGLFW_MOUSE_BUTTON_MIDDLE\fP   \fBGLFW_MOUSE_BUTTON_3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_MOUSE_BUTTON_1   0"

.PP
Definition at line 422 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_2   1"

.PP
Definition at line 423 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_3   2"

.PP
Definition at line 424 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_4   3"

.PP
Definition at line 425 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_5   4"

.PP
Definition at line 426 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_6   5"

.PP
Definition at line 427 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_7   6"

.PP
Definition at line 428 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_8   7"

.PP
Definition at line 429 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_LAST   \fBGLFW_MOUSE_BUTTON_8\fP"

.PP
Definition at line 430 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_LEFT   \fBGLFW_MOUSE_BUTTON_1\fP"

.PP
Definition at line 431 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_MIDDLE   \fBGLFW_MOUSE_BUTTON_3\fP"

.PP
Definition at line 433 of file glfw3\&.h\&.
.SS "#define GLFW_MOUSE_BUTTON_RIGHT   \fBGLFW_MOUSE_BUTTON_2\fP"

.PP
Definition at line 432 of file glfw3\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
