.TH "src/RenderDeviceOGL3x/DLLExport.cpp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RenderDeviceOGL3x/DLLExport.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Logger\&.h'\fP
.br
\fC#include 'RenderDeviceOGL3x\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBACTK::__declspec\fP (dllexport) IRenderDevice *CreateRenderDevice(HINSTANCE hInstance"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "IRenderDevice * \fBACTK::result\fP = nullptr"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
