.TH "Error codes" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Error codes \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_NOT_INITIALIZED\fP   0x00010001"
.br
.RI "\fIGLFW has not been initialized\&. \fP"
.ti -1c
.RI "#define \fBGLFW_NO_CURRENT_CONTEXT\fP   0x00010002"
.br
.RI "\fINo context is current for this thread\&. \fP"
.ti -1c
.RI "#define \fBGLFW_INVALID_ENUM\fP   0x00010003"
.br
.RI "\fIOne of the enum parameters for the function was given an invalid enum\&. \fP"
.ti -1c
.RI "#define \fBGLFW_INVALID_VALUE\fP   0x00010004"
.br
.RI "\fIOne of the parameters for the function was given an invalid value\&. \fP"
.ti -1c
.RI "#define \fBGLFW_OUT_OF_MEMORY\fP   0x00010005"
.br
.RI "\fIA memory allocation failed\&. \fP"
.ti -1c
.RI "#define \fBGLFW_API_UNAVAILABLE\fP   0x00010006"
.br
.RI "\fIGLFW could not find support for the requested client API on the system\&. \fP"
.ti -1c
.RI "#define \fBGLFW_VERSION_UNAVAILABLE\fP   0x00010007"
.br
.RI "\fIThe requested client API version is not available\&. \fP"
.ti -1c
.RI "#define \fBGLFW_PLATFORM_ERROR\fP   0x00010008"
.br
.RI "\fIA platform-specific error occurred that does not match any of the more specific categories\&. \fP"
.ti -1c
.RI "#define \fBGLFW_FORMAT_UNAVAILABLE\fP   0x00010009"
.br
.RI "\fIThe clipboard did not contain data in the requested format\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_API_UNAVAILABLE   0x00010006"

.PP
GLFW could not find support for the requested client API on the system\&. 
.PP
Definition at line 480 of file glfw3\&.h\&.
.SS "#define GLFW_FORMAT_UNAVAILABLE   0x00010009"

.PP
The clipboard did not contain data in the requested format\&. 
.PP
Definition at line 490 of file glfw3\&.h\&.
.SS "#define GLFW_INVALID_ENUM   0x00010003"

.PP
One of the enum parameters for the function was given an invalid enum\&. 
.PP
Definition at line 470 of file glfw3\&.h\&.
.SS "#define GLFW_INVALID_VALUE   0x00010004"

.PP
One of the parameters for the function was given an invalid value\&. 
.PP
Definition at line 473 of file glfw3\&.h\&.
.SS "#define GLFW_NO_CURRENT_CONTEXT   0x00010002"

.PP
No context is current for this thread\&. 
.PP
Definition at line 466 of file glfw3\&.h\&.
.SS "#define GLFW_NOT_INITIALIZED   0x00010001"

.PP
GLFW has not been initialized\&. 
.PP
Definition at line 463 of file glfw3\&.h\&.
.SS "#define GLFW_OUT_OF_MEMORY   0x00010005"

.PP
A memory allocation failed\&. 
.PP
Definition at line 476 of file glfw3\&.h\&.
.SS "#define GLFW_PLATFORM_ERROR   0x00010008"

.PP
A platform-specific error occurred that does not match any of the more specific categories\&. 
.PP
Definition at line 487 of file glfw3\&.h\&.
.SS "#define GLFW_VERSION_UNAVAILABLE   0x00010007"

.PP
The requested client API version is not available\&. 
.PP
Definition at line 483 of file glfw3\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
