.TH "GLFWvidmode" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWvidmode \- 
.PP
Video mode type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBredBits\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgreenBits\fP"
.br
.ti -1c
.RI "\fBint\fP \fBblueBits\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefreshRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Video mode type\&. 

This describes a single video mode\&. 
.PP
Definition at line 795 of file glfw3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLFWvidmode::blueBits"
The bit depth of the blue channel of the video mode\&. 
.PP
Definition at line 811 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWvidmode::greenBits"
The bit depth of the green channel of the video mode\&. 
.PP
Definition at line 808 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWvidmode::height"
The height, in screen coordinates, of the video mode\&. 
.PP
Definition at line 802 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWvidmode::redBits"
The bit depth of the red channel of the video mode\&. 
.PP
Definition at line 805 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWvidmode::refreshRate"
The refresh rate, in Hz, of the video mode\&. 
.PP
Definition at line 814 of file glfw3\&.h\&.
.SS "\fBint\fP GLFWvidmode::width"
The width, in screen coordinates, of the video mode\&. 
.PP
Definition at line 799 of file glfw3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
