.TH "GLFWgammaramp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWgammaramp \- 
.PP
Gamma ramp\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short * \fBred\fP"
.br
.ti -1c
.RI "unsigned short * \fBgreen\fP"
.br
.ti -1c
.RI "unsigned short * \fBblue\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamma ramp\&. 

This describes the gamma ramp for a monitor\&.
.PP
\fBSee Also:\fP
.RS 4
\fBglfwGetGammaRamp\fP \fBglfwSetGammaRamp\fP 
.RE
.PP

.PP
Definition at line 825 of file glfw3\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned short* GLFWgammaramp::blue"
An array of value describing the response of the blue channel\&. 
.PP
Definition at line 835 of file glfw3\&.h\&.
.SS "unsigned short* GLFWgammaramp::green"
An array of value describing the response of the green channel\&. 
.PP
Definition at line 832 of file glfw3\&.h\&.
.SS "unsigned short* GLFWgammaramp::red"
An array of value describing the response of the red channel\&. 
.PP
Definition at line 829 of file glfw3\&.h\&.
.SS "unsigned \fBint\fP GLFWgammaramp::size"
The number of elements in each array\&. 
.PP
Definition at line 838 of file glfw3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
