.TH "GLXBufferClobberEventSGIX" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXBufferClobberEventSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "\fBint\fP \fBevent_type\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1246 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXBufferClobberEventSGIX::count"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "Display* GLXBufferClobberEventSGIX::display"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::draw_type"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBGLXDrawable\fP GLXBufferClobberEventSGIX::drawable"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::event_type"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::height"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "unsigned \fBint\fP GLXBufferClobberEventSGIX::mask"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "Bool GLXBufferClobberEventSGIX::send_event"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "unsigned long GLXBufferClobberEventSGIX::serial"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::type"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::width"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::x"

.PP
Definition at line 1246 of file glxew\&.h\&.
.SS "\fBint\fP GLXBufferClobberEventSGIX::y"

.PP
Definition at line 1246 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
