.TH "GLXHyperpipeConfigSGIX" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBchannel\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBparticipationType\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtimeSlice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1174 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXHyperpipeConfigSGIX::channel"

.PP
Definition at line 1176 of file glxew\&.h\&.
.SS "unsigned \fBint\fP GLXHyperpipeConfigSGIX::participationType"

.PP
Definition at line 1177 of file glxew\&.h\&.
.SS "char GLXHyperpipeConfigSGIX::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Definition at line 1175 of file glxew\&.h\&.
.SS "\fBint\fP GLXHyperpipeConfigSGIX::timeSlice"

.PP
Definition at line 1178 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
