.TH "GLXPipeRect" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1180 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXPipeRect::destHeight"

.PP
Definition at line 1189 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destWidth"

.PP
Definition at line 1188 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destXOrigin"

.PP
Definition at line 1186 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::destYOrigin"

.PP
Definition at line 1187 of file glxew\&.h\&.
.SS "char GLXPipeRect::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Definition at line 1181 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcHeight"

.PP
Definition at line 1185 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcWidth"

.PP
Definition at line 1184 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcXOrigin"

.PP
Definition at line 1182 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcYOrigin"

.PP
Definition at line 1183 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
