.TH "GLXPipeRectLimits" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRectLimits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxWidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1167 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP GLXPipeRectLimits::maxHeight"

.PP
Definition at line 1171 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::maxWidth"

.PP
Definition at line 1172 of file glxew\&.h\&.
.SS "char GLXPipeRectLimits::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Definition at line 1168 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::XOrigin"

.PP
Definition at line 1169 of file glxew\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::YOrigin"

.PP
Definition at line 1170 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
