.TH "GLXPbufferClobberEvent" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPbufferClobberEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxew\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevent_type\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBbuffer_mask\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBaux_buffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 265 of file glxew\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned \fBint\fP GLXPbufferClobberEvent::aux_buffer"

.PP
Definition at line 273 of file glxew\&.h\&.
.SS "unsigned \fBint\fP GLXPbufferClobberEvent::buffer_mask"

.PP
Definition at line 272 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::count"

.PP
Definition at line 276 of file glxew\&.h\&.
.SS "Display* GLXPbufferClobberEvent::display"

.PP
Definition at line 270 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::draw_type"

.PP
Definition at line 267 of file glxew\&.h\&.
.SS "\fBGLXDrawable\fP GLXPbufferClobberEvent::drawable"

.PP
Definition at line 271 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::event_type"

.PP
Definition at line 266 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::height"

.PP
Definition at line 275 of file glxew\&.h\&.
.SS "Bool GLXPbufferClobberEvent::send_event"

.PP
Definition at line 269 of file glxew\&.h\&.
.SS "unsigned long GLXPbufferClobberEvent::serial"

.PP
Definition at line 268 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::width"

.PP
Definition at line 275 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::x"

.PP
Definition at line 274 of file glxew\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::y"

.PP
Definition at line 274 of file glxew\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
