.TH "samples/HelloWorld/HelloWorld.cpp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/HelloWorld/HelloWorld.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ACTK\&.h'\fP
.br
\fC#include 'RenderDeviceManager\&.h'\fP
.br
\fC#include <cstdint>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main ()"

.PP
Definition at line 6 of file HelloWorld\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
