.TH "C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/IGraphicsWindow.h" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/IGraphicsWindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ACTK\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include 'IRenderContext\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBACTK::IGraphicsWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< IGraphicsWindow > \fBACTK::GraphicsWindowPtr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
