.TH "C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/IRenderContext.h" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Artur/Documents/Visual Studio 2012/Projects/Games/Acagamic-Toolkit/include/IRenderContext.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ACTK\&.h'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include 'ClearState\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBACTK::IRenderContext\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr
.br
< IRenderContext > \fBACTK::RenderContextPtr\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBACTK::PrimitiveType\fP : char { \fBACTK::PrimitiveType::POINTS\fP, \fBACTK::PrimitiveType::LINE\fP, \fBACTK::PrimitiveType::LINES\fP, \fBACTK::PrimitiveType::LINE_STRIP\fP, \fBACTK::PrimitiveType::LINE_LOOP\fP, \fBACTK::PrimitiveType::TRIANGLES\fP, \fBACTK::PrimitiveType::TRIANGLE_STRIP\fP, \fBACTK::PrimitiveType::TRIANGLE_FAN\fP, \fBACTK::PrimitiveType::QUADS\fP, \fBACTK::PrimitiveType::QUAD_STRIP\fP, \fBACTK::PrimitiveType::POLYGON\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
