.TH "Modifier key flags" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modifier key flags \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_MOD_SHIFT\fP   0x0001"
.br
.RI "\fIIf this bit is set one or more Shift keys were held down\&. \fP"
.ti -1c
.RI "#define \fBGLFW_MOD_CONTROL\fP   0x0002"
.br
.RI "\fIIf this bit is set one or more Control keys were held down\&. \fP"
.ti -1c
.RI "#define \fBGLFW_MOD_ALT\fP   0x0004"
.br
.RI "\fIIf this bit is set one or more Alt keys were held down\&. \fP"
.ti -1c
.RI "#define \fBGLFW_MOD_SUPER\fP   0x0008"
.br
.RI "\fIIf this bit is set one or more Super keys were held down\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_MOD_ALT   0x0004"

.PP
If this bit is set one or more Alt keys were held down\&. 
.PP
Definition at line 412 of file glfw3\&.h\&.
.SS "#define GLFW_MOD_CONTROL   0x0002"

.PP
If this bit is set one or more Control keys were held down\&. 
.PP
Definition at line 409 of file glfw3\&.h\&.
.SS "#define GLFW_MOD_SHIFT   0x0001"

.PP
If this bit is set one or more Shift keys were held down\&. 
.PP
Definition at line 406 of file glfw3\&.h\&.
.SS "#define GLFW_MOD_SUPER   0x0008"

.PP
If this bit is set one or more Super keys were held down\&. 
.PP
Definition at line 415 of file glfw3\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
