.TH "src/Renderer/RenderDeviceManager.cpp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Renderer/RenderDeviceManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include 'RenderDeviceManager\&.h'\fP
.br
\fC#include 'IRenderDevice\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef IRenderDevice *(* \fBACTK::CREATERENDERDEVICE\fP )(HINSTANCE hInstance, EventLogger &logger)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
