.TH "samples/Triangle/resource.h" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/Triangle/resource.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSHADER\fP   256"
.br
.ti -1c
.RI "#define \fBIDS_VERTEXSHADER\fP   101"
.br
.ti -1c
.RI "#define \fBIDS_FRAGMENTSHADER\fP   102"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IDS_FRAGMENTSHADER   102"

.PP
Definition at line 3 of file resource\&.h\&.
.SS "#define IDS_VERTEXSHADER   101"

.PP
Definition at line 2 of file resource\&.h\&.
.SS "#define SHADER   256"

.PP
Definition at line 1 of file resource\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
