.TH "samples/Triangle/Triangle.cpp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/Triangle/Triangle.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ACTK\&.h'\fP
.br
\fC#include 'RenderDeviceManager\&.h'\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include 'resource\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::string\fP \fBLoadShader\fP (\fBint\fP \fBname\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstd::string\fP LoadShader (\fBint\fPname)"

.PP
Definition at line 7 of file Triangle\&.cpp\&.
.SS "\fBint\fP main ()"

.PP
Definition at line 18 of file Triangle\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
