.TH "src/RenderDeviceOGL3x/UniformUIOGL3x.cpp" 3 "Thu Apr 3 2014" "Acagamics Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/RenderDeviceOGL3x/UniformUIOGL3x.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'UniformOGL3x\&.h'\fP
.br
\fC#include 'GL\\glew\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include 'ACTK\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBACTK\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acagamics Toolkit from the source code\&.
